global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'envoy'
    metrics_path: /metrics
    static_configs:
      - targets: ['$DATABASE_IP_ADDR:9102', '$PRODUCT_IP_ADDR:9102']
        labels:
          group: 'envoy'